# Corrected FIELD_MAPPING for backend/routers/predict.py
# Replace the existing FIELD_MAPPING with this:

FIELD_MAPPING = {
    "academic_workload_unmanageable": "academic_workload_and_study_habits_i_find_my_academic_workload_unmanageable.",
    "confident_handling_challenges": "motivation_and_personal_accomplishment_i_feel_confident_in_handling_school_challenges.",
    "conflicts_at_home": "home_environment_and_personal_stress_i_experience_conflicts_or_tension_at_home.",
    "current_mode_affects_performance": "learning_modality_and_academic_impact_the_current_mode_of_learning_affects_my_academic_motivation_and_performance.",
    "difficulty_fall_asleep": "sleep_patterns_and_physical_health_i_find_it_difficult_to_fall_asleep_because_of_academic_stress.",
    "emotionally_drained_end_of_day": "emotional_state_and_burnout_indicators_i_feel_emotionally_drained_at_the_end_of_the_school_day.",
    "emotionally_unsupported": "home_environment_and_personal_stress_i_feel_emotionally_unsupported_by_my_family.",
    "family_does_not_understand": "home_environment_and_personal_stress_my_family_does_not_understand_or_acknowledge_my_academic_struggles.",
    "feel_burned_out": "emotional_state_and_burnout_indicators_i_feel_burned_out_even_when_i_try_to_rest.",
    "feel_competent": "motivation_and_personal_accomplishment_i_feel_competent_in_the_subjects_i’m_studying.",
    "feel_disconnected": "social_support_and_isolation_i_feel_disconnected_from_my_academic_community.",
    "feel_helpless": "emotional_state_and_burnout_indicators_i_feel_helpless_when_i_think_about_my_academic_performance.",
    "feel_in_control": "time_management_and_daily_routine_i_feel_in_control_of_how_i_manage_my_time.",
    "feel_isolated": "social_support_and_isolation_i_feel_isolated_or_alone_in_my_academic_journey.",
    "feel_like_giving_up": "emotional_state_and_burnout_indicators_i_sometimes_feel_like_giving_up_on_my_academic_goals.",
    "feel_more_isolated": "learning_modality_and_academic_impact_i_feel_more_isolated_in_online_or_hybrid_learning_environments.",
    "financial_difficulties": "home_environment_and_personal_stress_i_am_currently_experiencing_financial_difficulties_that_affect_my_studies.",
    "finish_before_deadline": "time_management_and_daily_routine_i_usually_finish_tasks_right_before_the_deadline.",
    "frequent_headaches_or_fatigue": "sleep_patterns_and_physical_health_i_experience_frequent_headaches_or_fatigue_during_the_semester.",
    "hard_to_feel_excited": "emotional_state_and_burnout_indicators_i_find_it_hard_to_feel_excited_about_academic_tasks.",
    "hard_to_focus": "emotional_state_and_burnout_indicators_i_find_it_hard_to_feel_excited_about_academic_tasks.",
    "hard_to_maintain_routine": "time_management_and_daily_routine_i_find_it_hard_to_maintain_a_consistent_daily_routine.",
    "hesitate_ask_help": "social_support_and_isolation_i_hesitate_to_ask_for_help_from_peers_or_instructors.",
    "irritated_easily": "emotional_state_and_burnout_indicators_i_get_irritated_or_frustrated_easily_because_of_school_pressure.",
    "learning_setup_stress": "learning_modality_and_academic_impact_my_learning_setup_online_hybrid_or_in_person_contributes_to_my_academic_stress.",
    "long_commutes_stress": "learning_modality_and_academic_impact_long_commutes_to_school_contribute_to_my_stress_and_burnout.",
    "lose_motivation_commute": "learning_modality_and_academic_impact_i_lose_motivation_after_a_long_commute",
    "miss_schoolwork": "home_environment_and_personal_stress_i_sometimes_miss_schoolwork_due_to_family_responsibilities.",
    "multitask_deadlines": "academic_workload_and_study_habits_i_often_multitask_to_meet_academic_deadlines.",
    "noisy_home_environment": "home_environment_and_personal_stress_my_home_environment_is_noisy_or_stressful_making_it_hard_to_study.",
    "not_accomplishing_anything": "motivation_and_personal_accomplishment_i_feel_like_i_am_not_accomplishing_anything_worthwhile_in_school.",
    "personal_life_affects_academics": "home_environment_and_personal_stress_i_feel_that_my_personal_or_home_life_affects_my_academic_performance.",
    "physically_exhausted": "sleep_patterns_and_physical_health_i_often_feel_physically_exhausted_even_after_taking_a_rest.",
    "prefer_current_modality": "learning_modality_and_academic_impact_i_prefer_my_current_learning_modality_over_other_options.",
    "pressure_support_family": "home_environment_and_personal_stress_i_often_feel_pressure_to_support_my_family_financially.",
    "proud_of_achievements": "motivation_and_personal_accomplishment_i_feel_proud_of_my_academic_achievements",
    "question_efforts": "motivation_and_personal_accomplishment_i_often_question_whether_my_efforts_in_school_are_worth_it.",
    "rarely_have_free_time": "academic_workload_and_study_habits_i_rarely_have_free_time_because_of_school_responsibilities.",
    "sacrifice_sleep": "academic_workload_and_study_habits_i_often_sacrifice_sleep_to_finish_schoolwork",
    "sense_of_dread": "emotional_state_and_burnout_indicators_i_feel_a_sense_of_dread_before_starting_school_related_task",
    "skip_meals_due_to_stress": "sleep_patterns_and_physical_health_i_skip_meals_due_to_my_school_workload_or_stress.",
    "sleep_less_than_6_hours": "sleep_patterns_and_physical_health_i_usually_get_less_than_6_hours_of_sleep_on_school_nights.",
    "someone_to_talk": "social_support_and_isolation_i_have_someone_to_talk_to_when_i_feel_burned_out.",
    "struggle_balance_responsibilities": "time_management_and_daily_routine_i_often_struggle_to_balance_school_and_personal_responsibilities.",
    "struggle_organize_tasks": "academic_workload_and_study_habits_i_struggle_to_organize_my_academic_tasks.",
    "study_under_pressure": "academic_workload_and_study_habits_i_usually_study_under_pressure_or_in_last_minute_situations.",
    "supported_by_family": "social_support_and_isolation_i_feel_supported_by_my_family_when_i_feel_stressed_about_school.",
    "traveling_affects_energy": "learning_modality_and_academic_impact_traveling_to_school_affects_my_energy_and_academic_performance._",
    "underperforming_peers": "motivation_and_personal_accomplishment_i_feel_i_am_underperforming_compared_to_my_peers",
    "use_planner": "academic_workload_and_study_habits_i_use_a_planner_or_schedule_to_track_deadlines.",
    "wake_up_tired": "sleep_patterns_and_physical_health_i_often_wake_up_feeling_tired_or_unrefreshed.",
    "waste_time": "time_management_and_daily_routine_i_waste_time_before_starting_my_schoolwork.",
    "workload_heavier_than_peers": "academic_workload_and_study_habits_i_believe_my_workload_is_heavier_than_that_of_my_peers.",
}
